### ISSUE TITLE
incomplete dataset

### ISSUE THREAD

**Issue by SidekickLx** [Henrygwb/deepvsa#2]
Hi,
First, thanks for providing the source code.
When I try to train the model in deepvsa folder. I found that there are two folders are needed at
https://github.com/Henrygwb/deepvsa/blob/ce68a5830f9edb2d382945e54db09abb696bf1d8/dlvsa/deepvsa.py#L425
AND
https://github.com/Henrygwb/deepvsa/blob/ce68a5830f9edb2d382945e54db09abb696bf1d8/dlvsa/deepvsa.py#L426

And I cannot find those two folders in the dataset you have given.
Is this part of the data could be generated by other tools provided in this repo? Or Could you please provide these two folders?
Thanks again!

**Comment by Henrygwb** [comment]
Hi, you actually don't need those things. The data are stored in the .npz format and can be accessed through the link provided in the README. Please set the "use_npz_train" in load_data() as 1 and use the truncated or non-truncated .npz data.
